NYC Open Data: 311 Service Requests
====================================
This notebook shows you how to load 311 calls into a pandas DataFrame.

It covers some basic pandas operations to explore and filter the data.

Read more about this dataset: <https://data.cityofnewyork.us/Social-Services/311-Service-Requests-from-2010-to-Present/erm2-nwe9/about_data>

_Note: this is written to load 1M 311 records. It takes around 3-4 minutes to run (for me).
You can load fewer records to play around with the data -- even 100 records was taking a couple of minutes._

In [1]:
import pandas as pd
# change this variable to load more of fewer records
# in python you can use _ to make large numbers more readable (optional)
num_records = 1_000_000
url = f"https://data.cityofnewyork.us/resource/erm2-nwe9.csv?$limit={num_records}"
df = pd.read_csv(url)
df.head()

/tmp/ipykernel_24137/3958818398.py:6: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,...,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
0,66648170,2025-10-29T01:36:54.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,11429.0,SPRINGFIELD BOULEVARD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,66647466,2025-10-29T01:35:52.000,2025-10-29T01:35:52.000,DOT,Department of Transportation,Street Condition,Pothole,NaN,11428.0,SPRINGFIELD BOULEVARD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,66646820,2025-10-29T01:35:32.000,NaN,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,Residential Building/House,11239.0,1165 ELTON STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.65606,-73.87372,"\n, \n(40.6560600695344, -73.87372031992082)"
3,66643705,2025-10-29T01:35:31.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,11428.0,SPRINGFIELD BOULEVARD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,66640718,2025-10-29T01:35:07.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,11428.0,SPRINGFIELD BOULEVARD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Use value_counts() to explore data
----------------------------------

In [2]:

# this will show us all of the unique `complaint_type` values and
# how many times each one appears in the dataset
df["complaint_type"].value_counts()

complaint_type
Illegal Parking            170569
Noise - Residential        128891
Noise - Street/Sidewalk     70914
Blocked Driveway            48994
HEAT/HOT WATER              28882
                            ...
DEP Highway Condition           1
DSNY Internal                   1
FHV Licensee Complaint          1
Calorie Labeling                1
Oil or Gas Spill                1
Name: count, Length: 179, dtype: int64

In [3]:
# create a new dataframe with the to 20 complaints
complaints = df["complaint_type"].value_counts().head(20)
complaints = pd.DataFrame(complaints).reset_index()
complaints

                complaint_type   count
0              Illegal Parking  170569
1          Noise - Residential  128891
2      Noise - Street/Sidewalk   70914
3             Blocked Driveway   48994
4               HEAT/HOT WATER   28882
5                 Water System   23797
6         UNSANITARY CONDITION   22537
7              Dirty Condition   20904
8            Abandoned Vehicle   20310
9           Noise - Commercial   19504
10            Street Condition   18969
11                  Encampment   16865
12                       Noise   16854
13  Homeless Person Assistance   15204
14             Noise - Vehicle   13850
15           Derelict Vehicles   13063
16           Missed Collection   13020
17             Illegal Dumping   12687
18               Drug Activity   12253
19    Traffic Signal Condition   11452

In [5]:
# get just the parking complaints
parking = df[df.complaint_type == "Illegal Parking"]
# we can look at the "descriptor" column for more details
parking["descriptor"].value_counts()

descriptor
Blocked Hydrant                   45223
Posted Parking Sign Violation     39800
Blocked Sidewalk                  26233
Commercial Overnight Parking      13622
Double Parked Blocking Traffic     9433
Blocked Crosswalk                  9061
Parking Permit Improper Use        6884
Blocked Bike Lane                  6110
License Plate Obscured             4611
Double Parked Blocking Vehicle     4475
Paper License Plates               2082
Unauthorized Bus Layover           1387
Overnight Commercial Storage       1179
Detached Trailer                    469
Name: count, dtype: int64

In [6]:
# save the dataframe to a CSV file so we don't need to load it from Open Data again
df.to_csv("nyc-311.csv", index=False)